#define PICKUP_SOUND_VOLUME_MIN 20
#define PICKUP_SOUND_VOLUME_MAX 60
#define DROP_SOUND_VOLUME_MIN 20
#define DROP_SOUND_VOLUME_MAX 70
#define THROW_SOUND_VOLUME 90

//Sound environment defines. Reverb preset for sounds played in an area, see sound datum reference for more.
#define GENERIC 0
#define PADDED_CELL 1
#define ROOM 2
#define BATHROOM 3
#define LIVINGROOM 4
#define STONEROOM 5
#define AUDITORIUM 6
#define CONCERT_HALL 7
#define CAVE 8
#define ARENA 9
#define HANGAR 10
#define CARPETED_HALLWAY 11
#define HALLWAY 12
#define STONE_CORRIDOR 13
#define ALLEY 14
#define FOREST 15
#define CITY 16
#define MOUNTAINS 17
#define QUARRY 18
#define PLAIN 19
#define PARKING_LOT 20
#define SEWER_PIPE 21
#define UNDERWATER 22
#define DRUGGED 23
#define DIZZY 24
#define PSYCHOTIC 25

#define STANDARD_STATION STONEROOM
#define LARGE_ENCLOSED HANGAR
#define SMALL_ENCLOSED BATHROOM
#define TUNNEL_ENCLOSED CAVE
#define LARGE_SOFTFLOOR CARPETED_HALLWAY
#define MEDIUM_SOFTFLOOR LIVINGROOM
#define SMALL_SOFTFLOOR ROOM
#define ASTEROID CAVE
#define SPACE UNDERWATER

///SFX list

#define SFX_SHATTER "shatter"
#define SFX_EXPLOSION  "explosion"
#define SFX_SPARK "sparks"
#define SFX_RUSTLE "rustle"
#define SFX_PUNCH "punch"
#define SFX_CLOWN "clownstep"
#define SFX_HISS "hiss"
#define SFX_CHOP "chop"
#define SFX_SWING_HIT "swing_hit"
#define SFX_PAGETURN "pageturn"
#define SFX_BONE_FRACTURE "fracture"
#define SFX_WOUND_CRACK "crack"
#define SFX_WOUND_SIZZLE "sizzle"
#define SFX_LIGHTER "light_bic"
#define SFX_KEYBOARD "keyboard"
#define SFX_KEYSTROKE "keystroke"
#define SFX_MACHINE_SWITCH "switch"
#define SFX_MACHINE_BUTTON "button"
#define SFX_GLASS_CRACK "glasscrack"
#define SFX_TRAY_HIT "tray_hit"
#define SFX_GUN_T12 "gun_t12"
#define SFX_BULLET_INSERT "sfx_bullet_insert"
#define SFX_SHELL_INSERT "sfx_shell_insert"
#define SFX_ZOMBIE "zombie_sound"
#define SFX_SCARY_SOUND "scary_sound"
#define SFX_SCP1507_ATTACK "1507_attack"

// FEMALE EMOTES
#define SFX_FEMALE_INTERNAL_BREATH  "female_internal_breath"
#define SFX_FEMALE_COUGH            "female_cough"
#define SFX_FEMALE_SNEEZE           "female_sneeze"
#define SFX_FEMALE_HEAVY_BREATH     "female_heavy_breath"
#define SFX_FEMALE_PAIN             "female_pain"
#define SFX_FEMALE_LONG_SCREAM      "female_long_scream"
#define SFX_FEMALE_FALL_ALIVE       "female_fall_alive"
#define SFX_FEMALE_FALL_DEAD        "female_fall_dead"
#define SFX_FEMALE_CRY              "female_cry"
#define SFX_FEMALE_LAUGH            "female_laugh"
#define SFX_FEMALE_YAWN             "female_yawn"
#define SFX_FEMALE_SIGH             "female_sigh"
#define SFX_FEMALE_MOAN            "female_moan"

// MALE EMOTES
#define SFX_MALE_INTERNAL_BREATH    "male_internal_breath"
#define SFX_MALE_COUGH              "male_cough"
#define SFX_MALE_SNEEZE             "male_sneeze"
#define SFX_MALE_HEAVY_BREATH       "male_heavy_breath"
#define SFX_MALE_PAIN               "male_pain"
#define SFX_MALE_LONG_SCREAM        "male_long_scream"
#define SFX_MALE_FALL_ALIVE         "male_fall_alive"
#define SFX_MALE_FALL_DEAD          "male_fall_dead"
#define SFX_MALE_CRY                "male_cry"
#define SFX_MALE_LAUGH              "male_laugh"
#define SFX_MALE_YAWN               "male_yawn"
#define SFX_MALE_SIGH               "male_sigh"
#define SFX_MALE_MOAN              "male_moan"

// MISC
#define SFX_VENT                    "vent"
#define SFX_GLASS_HIT               "glass_hit"
#define SFX_CHAINSAW                "chainsaw"
#define SFX_GLASS_KNOCK             "glass_knock"
#define SFX_GIB                     "gib"
#define SFX_HEELS                   "heels"
#define SFX_WHISTLE                 "whistle"
#define SFX_SNORE                   "snore"
#define SFX_CLAP                    "clap"
#define SFX_TRR                     "trr"
#define SFX_RADIO                   "radio"
#define SFX_THROWING                "throwing"
#define SFX_DISPOSAL                "disposal"
#define SFX_OINK                    "oink"
#define SFX_PLANTCROSS              "plantcross"
#define SFX_THUNDER                 "thunder"
#define SFX_SHOE_COVERS             "shoe_covers"
#define SFX_GLASSES_CLINK           "glasses_clink"
#define SFX_SUPERMATTER             "supermatter"

// PICKUP
#define SFX_PICKUP_GENERIC          "pickup_generic"
#define SFX_PICKUP_ACCESSORY        "pickup_accessory"
#define SFX_PICKUP_AMMOBOX          "pickup_ammobox"
#define SFX_PICKUP_AXE              "pickup_axe"
#define SFX_PICKUP_BACKPACK         "pickup_backpack"
#define SFX_PICKUP_BALL             "pickup_ball"
#define SFX_PICKUP_BOOK             "pickup_book"
#define SFX_PICKUP_BOOTS            "pickup_boots"
#define SFX_PICKUP_BOTTLE           "pickup_bottle"
#define SFX_PICKUP_GLASSBOTTLE      "pickup_glassbottle"
#define SFX_PICKUP_CARD             "pickup_card"
#define SFX_PICKUP_CARDBOARD        "pickup_cardboard"
#define SFX_PICKUP_CLOTH            "pickup_cloth"
#define SFX_PICKUP_COMPONENT        "pickup_component"
#define SFX_PICKUP_CROWBAR          "pickup_crowbar"
#define SFX_PICKUP_DEVICE           "pickup_device"
#define SFX_PICKUP_DISK             "pickup_disk"
#define SFX_PICKUP_DRINKGLASS       "pickup_drinkglass"
#define SFX_PICKUP_FLESH            "pickup_flesh"
#define SFX_PICKUP_FOOD             "pickup_food"
#define SFX_PICKUP_GASCAN           "pickup_gascan"
#define SFX_PICKUP_GLASS            "pickup_glass"
#define SFX_PICKUP_GLASSSMALL       "pickup_glasssmall"
#define SFX_PICKUP_GLOVES           "pickup_gloves"
#define SFX_PICKUP_GUN              "pickup_gun"
#define SFX_PICKUP_HAT              "pickup_hat"
#define SFX_PICKUP_HELMET           "pickup_helmet"
#define SFX_PICKUP_HERB             "pickup_herb"
#define SFX_PICKUP_KNIFE            "pickup_knife"
#define SFX_PICKUP_LEATHER          "pickup_leather"
#define SFX_PICKUP_MATCHBOX         "pickup_matchbox"
#define SFX_PICKUP_METALPOT         "pickup_metalpot"
#define SFX_PICKUP_METALWEAPON      "pickup_metalweapon"
#define SFX_PICKUP_MULTITOOL        "pickup_multitool"
#define SFX_PICKUP_PAPER            "pickup_paper"
#define SFX_PICKUP_PAPERCUP         "pickup_papercup"
#define SFX_PICKUP_PILLBOTTLE       "pickup_pillbottle"
#define SFX_PICKUP_PLUSHIE          "pickup_plushie"
#define SFX_PICKUP_RING             "pickup_ring"
#define SFX_PICKUP_RUBBER           "pickup_rubber"
#define SFX_PICKUP_SCREWDRIVER      "pickup_screwdriver"
#define SFX_PICKUP_SHEL              "pickup_shelldrop"
#define SFX_PICKUP_SHOES            "pickup_shoes"
#define SFX_PICKUP_SHOVEL           "pickup_shovel"
#define SFX_PICKUP_SODACAN          "pickup_sodacan"
#define SFX_PICKUP_SWORD            "pickup_sword"
#define SFX_PICKUP_TOOLBELT         "pickup_toolbelt"
#define SFX_PICKUP_TOOLBOX          "pickup_toolbox"
#define SFX_PICKUP_WELDINGTOOL      "pickup_weldingtool"
#define SFX_PICKUP_WIRECUTTER       "pickup_wirecutter"
#define SFX_PICKUP_WOODEN           "pickup_wooden"
#define SFX_PICKUP_WRAPPER          "pickup_wrapper"
#define SFX_PICKUP_WRENCH           "pickup_wrench"

// DROP
#define SFX_DROP_GENERIC            "drop_generic"
#define SFX_DROP_ACCESSORY          "drop_accessory"
#define SFX_DROP_AMMOBOX            "drop_ammobox"
#define SFX_DROP_AXE                "drop_axe"
#define SFX_DROP_BACKPACK           "drop_backpack"
#define SFX_DROP_BALL               "drop_ball"
#define SFX_DROP_BOOK               "drop_book"
#define SFX_DROP_BOOTS              "drop_boots"
#define SFX_DROP_BOTTLE             "drop_bottle"
#define SFX_DROP_GLASSBOTTLE        "drop_glassbottle"
#define SFX_DROP_CARD               "drop_card"
#define SFX_DROP_CARDBOARD          "drop_cardboard"
#define SFX_DROP_CLOTH              "drop_cloth"
#define SFX_DROP_COMPONENT          "drop_component"
#define SFX_DROP_CROWBAR            "drop_crowbar"
#define SFX_DROP_DEVICE             "drop_device"
#define SFX_DROP_DISK               "drop_disk"
#define SFX_DROP_DRINKGLASS         "drop_drinkglass"
#define SFX_DROP_FLESH              "drop_flesh"
#define SFX_DROP_FOOD               "drop_food"
#define SFX_DROP_GASCAN             "drop_gascan"
#define SFX_DROP_GLASS              "drop_glass"
#define SFX_DROP_GLASSSMALL         "drop_glasssmall"
#define SFX_DROP_GLOVES             "drop_gloves"
#define SFX_DROP_GUN                "drop_gun"
#define SFX_DROP_HAT                "drop_hat"
#define SFX_DROP_HELMET             "drop_helmet"
#define SFX_DROP_HERB               "drop_herb"
#define SFX_DROP_KNIFE              "drop_knife"
#define SFX_DROP_LEATHER            "drop_leather"
#define SFX_DROP_MATCHBOX           "drop_matchbox"
#define SFX_DROP_METALPOT           "drop_metalpot"
#define SFX_DROP_METALWEAPON        "drop_metalweapon"
#define SFX_DROP_MULTITOOL          "drop_multitool"
#define SFX_DROP_PAPER              "drop_paper"
#define SFX_DROP_PAPERCUP           "drop_papercup"
#define SFX_DROP_PILLBOTTLE         "drop_pillbottle"
#define SFX_DROP_PLUSHIE            "drop_plushie"
#define SFX_DROP_RING               "drop_ring"
#define SFX_DROP_RUBBER             "drop_rubber"
#define SFX_DROP_SCREWDRIVER        "drop_screwdriver"
#define SFX_DROP_SHELL              "drop_shelldrop"
#define SFX_DROP_SHOES              "drop_shoes"
#define SFX_DROP_SHOVEL             "drop_shovel"
#define SFX_DROP_SODACAN            "drop_sodacan"
#define SFX_DROP_SWORD              "drop_sword"
#define SFX_DROP_TOOLBELT           "drop_toolbelt"
#define SFX_DROP_TOOLBOX            "drop_toolbox"
#define SFX_DROP_WELDINGTOOL        "drop_weldingtool"
#define SFX_DROP_WIRECUTTER         "drop_wirecutter"
#define SFX_DROP_WOODEN             "drop_wooden"
#define SFX_DROP_WRAPPER            "drop_wrapper"
#define SFX_DROP_WRENCH             "drop_wrench"

// WEAPONS
#define SFX_SILENT_FIRE             "silent_fire"
