
name: Generate web assets
on:
  push:
    branches:
    - dev
jobs:
  generate_static_assets:
    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
    runs-on: ubuntu-latest
    concurrency: gen-assets
    steps:
      - uses: actions/checkout@v3
      - name: Generate static assets
        run: |
          mv tgui/public/ assets
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          BRANCH: gh-pages
          CLEAN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SINGLE_COMMIT: true
          FOLDER: assets
